#!/usr/bin/env tsx
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import type { Test } from "@composed/domain";
import { parseMarkdown } from "../src/lib/content/parse-md";
import { SAMPLE_MOCK } from "../src/lib/content/sample-mock";
import { AUTHORED_TESTS } from "../src/lib/content/authored";

// Compiles an authored markdown test into a committed TypeScript module.
//   pnpm content:build content/authored/my-mock.test.md
// See docs/content-authoring-format.md and ADR-0008.

const WEB_ROOT = resolve(__dirname, "..");
const PUBLIC_DIR = join(WEB_ROOT, "public");
const OUT_DIR = join(WEB_ROOT, "src/lib/content/authored");

const RED = "\x1b[31m";
const YELLOW = "\x1b[33m";
const GREEN = "\x1b[32m";
const DIM = "\x1b[2m";
const OFF = "\x1b[0m";

function main(): number {
  const input = process.argv[2];
  if (!input) {
    console.error("usage: pnpm content:build <file.test.md>");
    return 2;
  }
  // pnpm runs this with cwd=apps/web, so a path typed at the repo root would
  // resolve wrongly. INIT_CWD is where the user actually stood.
  const path = resolve(process.env.INIT_CWD ?? process.cwd(), input);
  if (!existsSync(path)) {
    console.error(`${RED}error${OFF} no such file: ${input}`);
    return 2;
  }

  const source = readFileSync(path, "utf8");
  const name = basename(path);
  const { test, diagnostics } = parseMarkdown(source, {
    audioExists: (src) => existsSync(join(PUBLIC_DIR, src.replace(/^\//, ""))),
    // Ids already claimed, so a new test cannot shadow an existing one.
    existingIds: [SAMPLE_MOCK.id, ...AUTHORED_TESTS.map((t) => t.id)],
  });

  for (const d of diagnostics) {
    const tag = d.severity === "error" ? `${RED}error${OFF}` : `${YELLOW}warn ${OFF}`;
    console.error(`${DIM}${name}:${d.line}${OFF}  ${tag}  ${d.message}`);
  }

  if (!test) {
    const errors = diagnostics.filter((d) => d.severity === "error").length;
    console.error(`\n${RED}✗${OFF} ${errors} error(s) — nothing written`);
    return 1;
  }

  const outFile = join(OUT_DIR, `${test.id}.ts`);
  writeFileSync(outFile, renderModule(test, name));
  const registered = regenerateIndex();

  const questions = test.sections
    .flatMap((s) => s.passages ?? [])
    .flatMap((p) => p.questionGroups)
    .flatMap((g) => g.questions).length;
  const prompts = test.sections.flatMap((s) => s.prompts ?? []).length;

  console.error(
    `\n${GREEN}✓${OFF} ${test.title}` +
      `\n  ${test.sections.map((s) => s.skill).join(" · ")}` +
      `\n  ${questions} question(s), ${prompts} prompt(s)` +
      `\n  wrote src/lib/content/authored/${test.id}.ts` +
      `\n  registered ${registered} test(s) in authored/index.ts` +
      `\n\n  ${DIM}commit both files, then check /tests${OFF}`
  );
  return 0;
}

function renderModule(test: Test, sourceName: string): string {
  return `import type { Test } from "@composed/domain";

// GENERATED by \`pnpm content:build\` from content/authored/${sourceName}.
// Do not edit by hand — your changes are lost on the next build.
// Edit the markdown source instead. See docs/content-authoring-format.md.
export const TEST: Test = ${JSON.stringify(test, null, 2)};
`;
}

/** Rewrites index.ts to static-import every generated test module. */
function regenerateIndex(): number {
  const modules = readdirSync(OUT_DIR)
    .filter((f) => f.endsWith(".ts") && f !== "index.ts")
    .sort();

  const imports = modules
    .map((f, i) => `import { TEST as t${i} } from "./${f.replace(/\.ts$/, "")}";`)
    .join("\n");
  const list = modules.map((_, i) => `t${i}`).join(", ");

  writeFileSync(
    join(OUT_DIR, "index.ts"),
    `import type { Test } from "@composed/domain";
${imports}

// GENERATED by \`pnpm content:build\` — do not edit by hand.
// Authored content is original or licensed, so unlike the Cambridge
// \`ingested/\` lane these files ARE committed and DO deploy. See ADR-0008.
export const AUTHORED_TESTS: Test[] = [${list}];
`
  );
  return modules.length;
}

process.exit(main());
